apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    run: grafana
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    run: grafana
status:
  loadBalancer: {}